// Copyright (c) 2020-2023 dotBunny Inc.
// dotBunny licenses this file to you under the BSL-1.0 license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using GDX.DataTables;
using UnityEditor;
using UnityEngine;

namespace GDX.Editor
{
    /// <summary>
    ///     A observer-like pattern for <see cref="DataTableBase" /> usage in the editor.
    /// </summary>
    /// <remarks>
    ///     This is useful for driving updates across multiple windows, inspectors and property drawers.
    /// </remarks>
    public static class DataTableTracker
    {
        /// <summary>
        ///     The registered <see cref="ICellValueChangedCallbackReceiver" />s by <see cref="DataTableBase" /> ticket.
        /// </summary>
        static readonly Dictionary<int, List<ICellValueChangedCallbackReceiver>> k_CellValueChangeCallbackReceivers =
            new Dictionary<int, List<ICellValueChangedCallbackReceiver>>(5);

        /// <summary>
        ///     The registered <see cref="IColumnDefinitionChangeCallbackReceiver" />s by <see cref="DataTableBase" /> ticket.
        /// </summary>
        static readonly Dictionary<int, List<IColumnDefinitionChangeCallbackReceiver>> k_ColumnChangeCallbackReceivers =
            new Dictionary<int, List<IColumnDefinitionChangeCallbackReceiver>>(5);

        /// <summary>
        ///     The registered <see cref="IRowDefinitionChangeCallbackReceiver" />s by <see cref="DataTableBase" /> ticket.
        /// </summary>
        static readonly Dictionary<int, List<IRowDefinitionChangeCallbackReceiver>> k_RowChangeCallbackReceivers =
            new Dictionary<int, List<IRowDefinitionChangeCallbackReceiver>>(5);

        /// <summary>
        ///     Next ticket to distribute when registering a <see cref="DataTableBase" />.
        /// </summary>
        static int s_TableTicketHead;

        /// <summary>
        ///     A mapping between tickets generated by <see cref="RegisterTable" /> and the provided <see cref="DataTableBase" />
        ///     s.
        /// </summary>
        static readonly Dictionary<int, DataTableBase> k_TableTicketToTable = new Dictionary<int, DataTableBase>(5);

        /// <summary>
        ///     A mapping between <see cref="RegisterTable" /> provided <see cref="DataTableBase" />s and tickets.
        /// </summary>
        static readonly Dictionary<DataTableBase, int> k_TableToTableTicket = new Dictionary<DataTableBase, int>(5);

        /// <summary>
        ///     A counter of usages, keyed by ticket.
        /// </summary>
        static readonly Dictionary<int, int> k_TableUsageCounters = new Dictionary<int, int>(5);

        /// <summary>
        ///     Indicate that a <see cref="DataTableBase" /> is being used by something.
        /// </summary>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void AddUsage(int tableTicket)
        {
            k_TableUsageCounters[tableTicket]++;
        }

        /// <summary>
        ///     Get the summary of currently what is being tracked by the <see cref="DataTableTracker" /> for a
        ///     <see cref="DataTableBase" />.
        /// </summary>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        /// <returns></returns>
        public static DataTableTrackerStats GetStats(int tableTicket)
        {
            DataTableTrackerStats stats = new DataTableTrackerStats();
            if (k_CellValueChangeCallbackReceivers.TryGetValue(tableTicket,
                    out List<ICellValueChangedCallbackReceiver> cellChange))
            {
                stats.CellValueChanged = cellChange.Count;
            }

            if (k_ColumnChangeCallbackReceivers.TryGetValue(tableTicket,
                    out List<IColumnDefinitionChangeCallbackReceiver> columnChange))
            {
                stats.ColumnDefinitionChange = columnChange.Count;
            }

            if (k_RowChangeCallbackReceivers.TryGetValue(tableTicket,
                    out List<IRowDefinitionChangeCallbackReceiver> rowChange))
            {
                stats.RowDefinitionChange = rowChange.Count;
            }

            if (k_TableUsageCounters.TryGetValue(tableTicket, out int usageCount))
            {
                stats.Usages = usageCount;
            }

            return stats;
        }

        /// <summary>
        ///     Attempt to get the registered <see cref="DataTableBase" /> by ticket number.
        /// </summary>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        /// <returns>A <see cref="DataTableBase" /> if found, otherwise null.</returns>
        public static DataTableBase GetTable(int tableTicket)
        {
            return k_TableTicketToTable.TryGetValue(tableTicket, out DataTableBase table) ? table : null;
        }

        /// <summary>
        ///     Attempt to get the ticket number of the provided <see cref="DataTableBase" />.
        /// </summary>
        /// <param name="dataTable">The target <see cref="DataTableBase" />.</param>
        /// <returns>A ticket number, otherwise -1.</returns>
        public static int GetTicket(DataTableBase dataTable)
        {
            if (dataTable == null)
            {
                return -1;
            }

            return k_TableToTableTicket.TryGetValue(dataTable, out int registerTable) ? registerTable : -1;
        }

        /// <summary>
        ///     Notify all registered <see cref="ICellValueChangedCallbackReceiver" />s that a change has occured.
        /// </summary>
        /// <remarks>Marks the changed <see cref="DataTableBase" /> as dirty.</remarks>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        /// <param name="rowIdentifier">The affected row's unique identifier.</param>
        /// <param name="columnIdentifier">The affected column's unique identifier.</param>
        /// <param name="ignoreReceiver">
        ///     A <see cref="ICellValueChangedCallbackReceiver" /> that should be ignored in the notification
        ///     process. This is used to stop self-notification.
        /// </param>
        public static void NotifyOfCellValueChange(int tableTicket, int rowIdentifier, int columnIdentifier,
            ICellValueChangedCallbackReceiver ignoreReceiver = null)
        {
            int count = k_CellValueChangeCallbackReceivers[tableTicket].Count;
            for (int i = 0; i < count; i++)
            {
                ICellValueChangedCallbackReceiver callback = k_CellValueChangeCallbackReceivers[tableTicket][i];
                if (callback != ignoreReceiver)
                {
                    callback.OnCellValueChanged(rowIdentifier, columnIdentifier);
                }
            }

            EditorUtility.SetDirty(k_TableTicketToTable[tableTicket]);
        }

        /// <summary>
        ///     Notify all registered <see cref="IColumnDefinitionChangeCallbackReceiver" />s that a change has occured.
        /// </summary>
        /// <remarks>Marks the changed <see cref="DataTableBase" /> as dirty.</remarks>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        /// <param name="columnIdentifier">The affected column's unique identifier.</param>
        /// <param name="ignoreReceiver">
        ///     A <see cref="IColumnDefinitionChangeCallbackReceiver" /> that should be ignored in the notification
        ///     process. This is used to stop self-notification.
        /// </param>
        public static void NotifyOfColumnChange(int tableTicket, int columnIdentifier,
            IColumnDefinitionChangeCallbackReceiver ignoreReceiver = null)
        {
            int count = k_ColumnChangeCallbackReceivers[tableTicket].Count;
            for (int i = 0; i < count; i++)
            {
                IColumnDefinitionChangeCallbackReceiver callback = k_ColumnChangeCallbackReceivers[tableTicket][i];
                if (callback != ignoreReceiver)
                {
                    callback.OnColumnDefinitionChange(columnIdentifier);
                }
            }

            EditorUtility.SetDirty(k_TableTicketToTable[tableTicket]);
        }

        /// <summary>
        ///     Notify all registered <see cref="IRowDefinitionChangeCallbackReceiver" />s that a change has occured.
        /// </summary>
        /// <remarks>Marks the changed <see cref="DataTableBase" /> as dirty.</remarks>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        /// <param name="rowIdentifier">The affected row's unique identifier.</param>
        /// <param name="ignoreReceiver">
        ///     A <see cref="IRowDefinitionChangeCallbackReceiver" /> that should be ignored in the notification
        ///     process. This is used to stop self-notification.
        /// </param>
        public static void NotifyOfRowChange(int tableTicket, int rowIdentifier,
            IRowDefinitionChangeCallbackReceiver ignoreReceiver = null)
        {
            int count = k_RowChangeCallbackReceivers[tableTicket].Count;
            for (int i = 0; i < count; i++)
            {
                IRowDefinitionChangeCallbackReceiver callback = k_RowChangeCallbackReceivers[tableTicket][i];
                if (callback != ignoreReceiver)
                {
                    callback.OnRowDefinitionChange(rowIdentifier);
                }
            }

            EditorUtility.SetDirty(k_TableTicketToTable[tableTicket]);
        }

        /// <summary>
        ///     Register an <see cref="ICellValueChangedCallbackReceiver" /> for callbacks based on the provided ticket.
        /// </summary>
        /// <param name="callback">The target receiver to add to the callback list.</param>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void RegisterCellValueChanged(ICellValueChangedCallbackReceiver callback, int tableTicket)
        {
            if (tableTicket == -1)
            {
                Debug.LogError("Unable to register for CellValueChanged callback as the ticket provided is invalid.");
                return;
            }

            if (!k_CellValueChangeCallbackReceivers.ContainsKey(tableTicket))
            {
                k_CellValueChangeCallbackReceivers.Add(tableTicket,
                    new List<ICellValueChangedCallbackReceiver>());
            }

            if (!k_CellValueChangeCallbackReceivers[tableTicket].Contains(callback))
            {
                k_CellValueChangeCallbackReceivers[tableTicket].Add(callback);
            }
        }

        /// <summary>
        ///     Register an <see cref="IColumnDefinitionChangeCallbackReceiver" /> for callbacks based on the provided ticket.
        /// </summary>
        /// <param name="callback">The target receiver to add to the callback list.</param>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void RegisterColumnChanged(IColumnDefinitionChangeCallbackReceiver callback, int tableTicket)
        {
            if (tableTicket == -1)
            {
                return;
            }

            if (!k_ColumnChangeCallbackReceivers.ContainsKey(tableTicket))
            {
                k_ColumnChangeCallbackReceivers.Add(tableTicket,
                    new List<IColumnDefinitionChangeCallbackReceiver>());
            }

            if (!k_ColumnChangeCallbackReceivers[tableTicket].Contains(callback))
            {
                k_ColumnChangeCallbackReceivers[tableTicket].Add(callback);
            }
        }

        /// <summary>
        ///     Register an <see cref="IRowDefinitionChangeCallbackReceiver" /> for callbacks based on the provided ticket.
        /// </summary>
        /// <param name="callback">The target receiver to add to the callback list.</param>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void RegisterRowChanged(IRowDefinitionChangeCallbackReceiver callback, int tableTicket)
        {
            if (tableTicket == -1)
            {
                return;
            }

            if (!k_RowChangeCallbackReceivers.ContainsKey(tableTicket))
            {
                k_RowChangeCallbackReceivers.Add(tableTicket,
                    new List<IRowDefinitionChangeCallbackReceiver>());
            }

            if (!k_RowChangeCallbackReceivers[tableTicket].Contains(callback))
            {
                k_RowChangeCallbackReceivers[tableTicket].Add(callback);
            }
        }

        /// <summary>
        ///     Registers a <see cref="DataTableBase" /> for use by all of the different supporting systems inside of the Unity
        ///     editor.
        /// </summary>
        /// <param name="dataTable">The <see cref="DataTableBase" /> to be registered for use.</param>
        /// <param name="forcedTicket">
        ///     Force a specific ticket to be used for a table; this is explicitly used during domain reload
        ///     to ensure references are kept.
        /// </param>
        /// <returns>A domain incremented ticket number.</returns>
        public static int RegisterTable(DataTableBase dataTable, int forcedTicket = -1)
        {
            // This is the scenario where we need to rebuild after domain reload
            if (forcedTicket != -1)
            {
                k_TableTicketToTable[forcedTicket] = dataTable;
                k_TableToTableTicket[dataTable] = forcedTicket;

#if UNITY_2022_2_OR_NEWER
                k_TableUsageCounters.TryAdd(forcedTicket, 0);
#else
                if (!k_TableUsageCounters.ContainsKey(forcedTicket))
                {
                    k_TableUsageCounters[forcedTicket] = 0;
                }
#endif // UNITY_2022_2_OR_NEWER

                if (forcedTicket >= s_TableTicketHead)
                {
                    s_TableTicketHead = forcedTicket + 1;
                }

                return forcedTicket;
            }

            if (k_TableToTableTicket.TryGetValue(dataTable, out int registerTable))
            {
                return registerTable;
            }

            // Register table
            int head = s_TableTicketHead;
            k_TableTicketToTable.Add(head, dataTable);
            k_TableToTableTicket.Add(dataTable, head);
            k_TableUsageCounters.Add(head, 0);

            // Increment our next head
            s_TableTicketHead++;
            return head;
        }

        /// <summary>
        ///     Indicate that a <see cref="DataTableBase" /> is no longer being used by something.
        /// </summary>
        /// <remarks>
        ///     When there are no more usages, a cleanup pass is ran to remove other mappings.
        /// </remarks>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void RemoveUsage(int tableTicket)
        {
            if (!k_TableUsageCounters.ContainsKey(tableTicket))
            {
                return;
            }

            k_TableUsageCounters[tableTicket]--;
            if (k_TableUsageCounters[tableTicket] > 0)
            {
                return;
            }

            k_TableToTableTicket.Remove(k_TableTicketToTable[tableTicket]);
            k_TableTicketToTable.Remove(tableTicket);
            k_TableUsageCounters.Remove(tableTicket);
        }

        /// <summary>
        ///     Unregister an <see cref="ICellValueChangedCallbackReceiver" /> from callbacks based on the provided ticket.
        /// </summary>
        /// <param name="callback">The target receiver to remove from the callback list.</param>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void UnregisterCellValueChanged(ICellValueChangedCallbackReceiver callback, int tableTicket)
        {
            if (k_CellValueChangeCallbackReceivers.TryGetValue(tableTicket,
                    out List<ICellValueChangedCallbackReceiver> receiver))
            {
                receiver.Remove(callback);
            }
        }

        /// <summary>
        ///     Unregister an <see cref="IColumnDefinitionChangeCallbackReceiver" /> from callbacks based on the provided ticket.
        /// </summary>
        /// <param name="callback">The target receiver to remove from the callback list.</param>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void UnregisterColumnChanged(IColumnDefinitionChangeCallbackReceiver callback, int tableTicket)
        {
            if (k_ColumnChangeCallbackReceivers.TryGetValue(tableTicket,
                    out List<IColumnDefinitionChangeCallbackReceiver> receiver))
            {
                receiver.Remove(callback);
            }
        }

        /// <summary>
        ///     Unregister an <see cref="IRowDefinitionChangeCallbackReceiver" /> from callbacks based on the provided ticket.
        /// </summary>
        /// <param name="callback">The target receiver to remove from the callback list.</param>
        /// <param name="tableTicket">The unique ticket generated by <see cref="RegisterTable" />.</param>
        public static void UnregisterRowChanged(IRowDefinitionChangeCallbackReceiver callback, int tableTicket)
        {
            if (k_RowChangeCallbackReceivers.TryGetValue(tableTicket,
                    out List<IRowDefinitionChangeCallbackReceiver> receiver))
            {
                receiver.Remove(callback);
            }
        }

        /// <summary>
        ///     Generates a weak-reference list of all <see cref="DataTableBase" /> based objects in the Asset Database.
        /// </summary>
        /// <returns>An array of <see cref="AssetDatabaseReference" />s.</returns>
        internal static AssetDatabaseReference[] FindTables()
        {
            List<AssetDatabaseReference> returnList = new List<AssetDatabaseReference>(5);

            // Get derived types
            TypeCache.TypeCollection tableTypeCollection = TypeCache.GetTypesDerivedFrom<DataTableBase>();
            int count = tableTypeCollection.Count;
            for (int i = 0; i < count; i++)
            {
                string typeDef = tableTypeCollection[i].ToString();
                string[] paths = AssetDatabase.FindAssets($"t:{typeDef}");
                int pathCount = paths.Length;
                for (int j = 0; j < pathCount; j++)
                {
                    returnList.Add(new AssetDatabaseReference(paths[j], tableTypeCollection[i].UnderlyingSystemType));
                }
            }

            return returnList.ToArray();
        }

        /// <summary>
        ///     A <see cref="DataTableTracker" /> based set of stats.
        /// </summary>
        public struct DataTableTrackerStats
        {
            public int CellValueChanged;
            public int ColumnDefinitionChange;
            public int RowDefinitionChange;
            public int Usages;
        }

        /// <summary>
        ///     An interface describing the functionality needed for an object to get a callback when a
        ///     a cell values changes in a <see cref="DataTableBase" />.
        /// </summary>
        public interface ICellValueChangedCallbackReceiver
        {
            /// <summary>
            ///     A cell value change has occured.
            /// </summary>
            /// <param name="rowIdentifier">The affected row's unique identifier.</param>
            /// <param name="columnIdentifier">The affected column's unique identifier.</param>
            void OnCellValueChanged(int rowIdentifier, int columnIdentifier);
        }

        /// <summary>
        ///     An interface describing the functionality needed for an object to get a callback when a
        ///     <see cref="ColumnDescription" /> changes in a <see cref="DataTableBase" />.
        /// </summary>
        public interface IColumnDefinitionChangeCallbackReceiver
        {
            /// <summary>
            ///     A <see cref="ColumnDescription" /> change has occured.
            /// </summary>
            /// <param name="columnIdentifier">The affected column's unique identifier.</param>
            void OnColumnDefinitionChange(int columnIdentifier);
        }

        /// <summary>
        ///     An interface describing the functionality needed for an object to get a callback when a
        ///     <see cref="RowDescription" /> changes in a <see cref="DataTableBase" />.
        /// </summary>
        public interface IRowDefinitionChangeCallbackReceiver
        {
            /// <summary>
            ///     A <see cref="RowDescription" /> change has occured.
            /// </summary>
            /// <param name="rowIdentifier">The affected row's unique identifier.</param>
            void OnRowDefinitionChange(int rowIdentifier);
        }
    }
}